version: '3.8'

services:
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - sneakers-backend

  sneakers-backend:
    image: golang:1.22
    ports:
      - "8080:8080"
    depends_on:
      - database
      - redis-cache-service

  database:
    image: postgres:15
    ports:
      - "8888:8888"

  redis-cache-service:
    image: redis:7
    ports:
      - "6379"
